# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

waxman <- function(n, a, d) {
    .Call('diseaseNetworks_waxman', PACKAGE = 'diseaseNetworks', n, a, d)
}

apply_cluster <- function(nodes, F, f) {
    .Call('diseaseNetworks_apply_cluster', PACKAGE = 'diseaseNetworks', nodes, F, f)
}

keeling <- function(n, F, f, a, d) {
    .Call('diseaseNetworks_keeling', PACKAGE = 'diseaseNetworks', n, F, f, a, d)
}

sim_epidemic <- function(edges, node_states, gamma, Beta, trace) {
    .Call('diseaseNetworks_sim_epidemic', PACKAGE = 'diseaseNetworks', edges, node_states, gamma, Beta, trace)
}

finalSize <- function(Beta, n) {
    .Call('diseaseNetworks_finalSize', PACKAGE = 'diseaseNetworks', Beta, n)
}

Prod <- function(a) {
    .Call('diseaseNetworks_Prod', PACKAGE = 'diseaseNetworks', a)
}

myWhich <- function(a, b) {
    .Call('diseaseNetworks_myWhich', PACKAGE = 'diseaseNetworks', a, b)
}

mle <- function(Ne, Beta) {
    .Call('diseaseNetworks_mle', PACKAGE = 'diseaseNetworks', Ne, Beta)
}

